---
name: Bug report
about: Create a report to help us improve
title: '[BUG] '
labels: bug
assignees: ''

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Start server with '...'
2. Send request to '....'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs**
If applicable, add logs to help explain your problem.
```
Paste logs here
```

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Go Version: [e.g. 1.21]
 - Version [e.g. 0.1.0]
 - Deployment: [e.g. Docker, Kubernetes, Binary]

**Additional context**
Add any other context about the problem here.
